version: '3.9'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: ${SA_PASSWORD}  # <- make sure this matches your .env
      POSTGRES_DB: EncoraOneGrievanceDB
    ports:
      - "1433:1433"
    
    restart: unless-stopped

  grievance_api:
    build:
      context: .
    ports:
      - "1433:5432"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=db,1433;Database=EncoraOneGrievanceDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      AllowedOrigins: http://localhost:5173
    depends_on:
      - db
      - migrator

  migrator:
    build:
      context: ./migrator
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: Server=db,1433;Database=EncoraOneGrievanceDB;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
    volumes:
      - ./.:/app
      - ./scripts:/scripts
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/scripts/migrator.sh"]
    restart: "no"


