version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: encoraone_postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: ${SA_PASSWORD}
      POSTGRES_DB: EncoraOneGrievanceDB
    ports:
      - "5432:5432"


  grievance_api:
    build:
      context: .
    container_name: grievance_api
    ports:
      - "5001:5001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # PostgreSQL connection string
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=EncoraOneGrievanceDB;Username=sa;Password=${SA_PASSWORD};
      AllowedOrigins: http://localhost:5173
    depends_on:
      - db
      - migrator

  migrator:
    build:
      context: ./migrator
    container_name: grievance_migrator
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=EncoraOneGrievanceDB;Username=sa;Password=${SA_PASSWORD};
    volumes:
      - ./.:/app
      - ./scripts:/scripts
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["/bin/bash", "/scripts/migrator.sh"]
    restart: "no"


